import { NextResponse } from "next/server";
import { ADMIN_EMAIL, readAdminSessionFromRequest } from "@/lib/admin-auth";
import { normalizeProductInput } from "@/lib/business-documents";
import { supabaseAdminFetch } from "@/lib/supabase-admin";

export const runtime = "nodejs";
async function audit(action: string, id: string) { await supabaseAdminFetch("/rest/v1/cms_audit_log", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify({ actor_email: ADMIN_EMAIL, action, resource: "products", record_id: id }) }); }
export async function PATCH(request: Request, context: { params: Promise<{id:string}> }) { if (!readAdminSessionFromRequest(request, true)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const { id } = await context.params; const record = normalizeProductInput(await request.json()); const response = await supabaseAdminFetch(`/rest/v1/business_products?id=eq.${encodeURIComponent(id)}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(record) }); if (!response.ok) throw new Error("Produk/layanan belum dapat diperbarui. Pastikan kode unik."); await audit("update", id); return NextResponse.json({ ok: true }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Produk/layanan belum dapat diperbarui." }, { status: 400 }); } }
export async function DELETE(request: Request, context: { params: Promise<{id:string}> }) { if (!readAdminSessionFromRequest(request, true)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { id } = await context.params; const response = await supabaseAdminFetch(`/rest/v1/business_products?id=eq.${encodeURIComponent(id)}`, { method: "DELETE", headers: { Prefer: "return=representation" } }); if (!response.ok) return NextResponse.json({ error: "Produk/layanan belum dapat dihapus." }, { status: 409 }); await audit("delete", id); return NextResponse.json({ ok: true }); }
