"use client";

import { useEffect, useMemo, useState } from "react";
import { invoiceTotal, type Invoice, type Payment } from "@/lib/business-documents";
import { formatRupiah } from "@/lib/quotations";

type AgingKey = "not_due" | "days_1_7" | "days_8_30" | "days_31_plus";
const agingLabels: Record<AgingKey, string> = { not_due: "Belum jatuh tempo", days_1_7: "Terlambat 1-7 hari", days_8_30: "Terlambat 8-30 hari", days_31_plus: "Terlambat >30 hari" };

export function BusinessDashboardPanel() {
  const [invoices, setInvoices] = useState<Invoice[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([fetch("/api/admin/business/invoices"), fetch("/api/admin/business/payments")]).then(async ([invoiceResponse, paymentResponse]) => { const [invoiceResult, paymentResult] = await Promise.all([invoiceResponse.json(), paymentResponse.json()]); if (!invoiceResponse.ok || !paymentResponse.ok) throw new Error(invoiceResult.error || paymentResult.error || "Dashboard belum dapat dimuat."); setInvoices(invoiceResult.records || []); setPayments(paymentResult.records || []); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "Dashboard belum dapat dimuat.")).finally(() => setLoading(false)); }, []);
  const rows = useMemo(() => { const paid = new Map<string, number>(); for (const payment of payments) if (payment.status === "confirmed") paid.set(payment.invoice_id, (paid.get(payment.invoice_id) || 0) + Number(payment.amount)); const today = new Date(); today.setHours(0,0,0,0); return invoices.filter((invoice) => !["draft", "cancelled", "paid"].includes(invoice.status)).map((invoice) => { const outstanding = Math.max(0, invoiceTotal(invoice) - (paid.get(invoice.id) || 0)); const due = new Date(`${invoice.due_date}T00:00:00`); const days = Math.max(0, Math.floor((today.getTime() - due.getTime()) / 86400000)); const bucket: AgingKey = due >= today ? "not_due" : days <= 7 ? "days_1_7" : days <= 30 ? "days_8_30" : "days_31_plus"; return { invoice, outstanding, days, bucket }; }).filter((row) => row.outstanding > 0); }, [invoices, payments]);
  const totals = useMemo(() => rows.reduce((result, row) => ({ ...result, [row.bucket]: result[row.bucket] + row.outstanding }), { not_due: 0, days_1_7: 0, days_8_30: 0, days_31_plus: 0 } as Record<AgingKey, number>), [rows]);
  if (loading) return <div className="admin-content"><div className="admin-loading">Memuat aging piutang…</div></div>;
  return <div className="admin-content admin-business-dashboard"><div className="admin-list-header"><div><h2>Aging piutang</h2><p>Saldo dihitung dari invoice terbuka dikurangi pembayaran berstatus confirmed.</p></div></div>{error && <p className="admin-form-message">{error}</p>}<section className="admin-stats admin-aging-stats">{(Object.keys(agingLabels) as AgingKey[]).map((key) => <article key={key}><span>{agingLabels[key]}</span><strong>{formatRupiah(totals[key])}</strong><small>{rows.filter((row) => row.bucket === key).length} invoice</small></article>)}</section><section className="admin-business-section"><div className="admin-list-header"><div><h2>Invoice outstanding</h2><p>Prioritaskan bucket paling lama dan customer dengan saldo terbesar.</p></div></div>{rows.length === 0 ? <div className="admin-empty-state"><strong>Tidak ada piutang terbuka</strong><p>Invoice sent atau partially paid akan tampil di sini.</p></div> : <div className="admin-payment-list">{rows.sort((a,b) => b.days - a.days).map(({ invoice, outstanding, days }) => <article key={invoice.id}><div><span>{days ? `${days} HARI TERLAMBAT` : "BELUM JATUH TEMPO"}</span><strong>{invoice.invoice_number} · {invoice.customer_company}</strong><small>Jatuh tempo {invoice.due_date}</small></div><div><strong>{formatRupiah(outstanding)}</strong><small>{invoice.status}</small></div></article>)}</div>}</section></div>;
}
