"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { invoiceStatuses, invoiceSubtotal, invoiceTotal, type Invoice, type InvoiceInput, type PaymentAccount } from "@/lib/business-documents";
import { formatRupiah, type Quotation, type QuotationItem } from "@/lib/quotations";

const labels: Record<string, string> = { draft: "Draft", sent: "Sent", partially_paid: "Partially paid", paid: "Paid", overdue: "Overdue", cancelled: "Cancelled" };
function isoDate(offset = 0) { const value = new Date(); value.setDate(value.getDate() + offset); return value.toISOString().slice(0, 10); }
function emptyItem(): QuotationItem { return { name: "", description: "", quantity: 1, unit: "paket", unitPrice: 0 }; }
function coerce(record: Invoice): Invoice { return { ...record, discount_amount: Number(record.discount_amount || 0), items: (record.items || []).map((item) => ({ ...item, quantity: Number(item.quantity), unitPrice: Number(item.unitPrice) })) }; }
function emptyInvoice(accounts: PaymentAccount[]): InvoiceInput {
  return { quotation_id: null, status: "draft", issue_date: isoDate(), due_date: isoDate(14), customer_company: "", customer_name: "", customer_email: "", customer_phone: "", customer_address: "", subject: "", items: [emptyItem()], discount_amount: 0, payment_account_id: accounts.find((account) => account.is_default && account.is_active)?.id || accounts.find((account) => account.is_active)?.id || "", payment_terms: "Pembayaran dilakukan melalui transfer ke rekening yang tercantum pada invoice.", notes: "Mohon mencantumkan nomor invoice pada berita transfer. Invoice ini bukan Faktur Pajak dan tidak memuat PPN karena RETECH saat ini Non-PKP." };
}
function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="admin-field"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} /></label>; }
function Area({ label, value, onChange, rows = 4 }: { label: string; value: string; onChange: (value: string) => void; rows?: number }) { return <label className="admin-field admin-field-wide"><span>{label}</span><textarea value={value} onChange={(event) => onChange(event.target.value)} rows={rows} /></label>; }

function InvoiceEditor({ invoice, accounts, quotations, onClose, onSaved }: { invoice: Invoice | null; accounts: PaymentAccount[]; quotations: Quotation[]; onClose: () => void; onSaved: () => void }) {
  const isNew = invoice == null;
  const [draft, setDraft] = useState<InvoiceInput>(() => invoice ? coerce(invoice) : emptyInvoice(accounts));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const subtotal = useMemo(() => invoiceSubtotal(draft), [draft]);
  const total = useMemo(() => invoiceTotal(draft), [draft]);
  const set = <K extends keyof InvoiceInput>(key: K, value: InvoiceInput[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const updateItem = (index: number, key: keyof QuotationItem, value: string | number) => set("items", draft.items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  function applyQuotation(id: string) {
    const quote = quotations.find((record) => record.id === id);
    if (!quote) { set("quotation_id", null); return; }
    setDraft((current) => ({ ...current, quotation_id: quote.id, customer_company: quote.customer_company, customer_name: quote.customer_name, customer_email: quote.customer_email || "", customer_phone: quote.customer_phone || "", customer_address: quote.customer_address || "", subject: quote.subject, items: quote.items.map((item) => ({ ...item, quantity: Number(item.quantity), unitPrice: Number(item.unitPrice) })), discount_amount: Number(quote.discount_amount || 0), payment_terms: quote.payment_terms || current.payment_terms }));
  }
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setError("");
    try {
      const response = await fetch(isNew ? "/api/admin/business/invoices" : `/api/admin/business/invoices/${invoice.id}`, { method: isNew ? "POST" : "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) });
      const result = await response.json() as { ok?: boolean; error?: string };
      if (!response.ok || !result.ok) throw new Error(result.error || "Invoice belum dapat disimpan.");
      onSaved();
    } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Invoice belum dapat disimpan."); setSaving(false); }
  }
  return <div className="admin-modal-backdrop"><section className="admin-modal admin-quotation-modal" role="dialog" aria-modal="true" aria-label={isNew ? "Buat invoice" : `Edit ${invoice.invoice_number}`}>
    <header><div><span className="admin-kicker">BUSINESS / INVOICE / {isNew ? "CREATE" : "UPDATE"}</span><h2>{isNew ? "Buat invoice profesional" : invoice.invoice_number}</h2></div><button type="button" onClick={onClose} aria-label="Tutup">×</button></header>
    <form onSubmit={save}>
      <section className="admin-quote-form-section"><div className="admin-editor-section-title"><div><h3>Dokumen</h3><p>Nomor invoice dibuat otomatis. Pilih quotation untuk menyalin customer, item, dan harga.</p></div><span className="admin-non-pkp-badge">NON-PKP / TANPA PPN</span></div><div className="admin-form-grid"><label className="admin-field"><span>Quotation referensi</span><select value={draft.quotation_id || ""} onChange={(event) => applyQuotation(event.target.value)}><option value="">Tanpa quotation</option>{quotations.map((quote) => <option value={quote.id} key={quote.id}>{quote.quote_number} - {quote.customer_company}</option>)}</select></label><label className="admin-field"><span>Status</span><select value={draft.status} onChange={(event) => set("status", event.target.value as InvoiceInput["status"])}>{invoiceStatuses.map((status) => <option value={status} key={status}>{labels[status]}</option>)}</select></label><Field label="Tanggal invoice" type="date" value={draft.issue_date} onChange={(value) => set("issue_date", value)} required /><Field label="Jatuh tempo" type="date" value={draft.due_date} onChange={(value) => set("due_date", value)} required /></div><Field label="Perihal / nama project" value={draft.subject} onChange={(value) => set("subject", value)} required /></section>
      <section className="admin-quote-form-section"><h3>Customer</h3><div className="admin-form-grid"><Field label="Nama perusahaan" value={draft.customer_company} onChange={(value) => set("customer_company", value)} required /><Field label="Nama PIC" value={draft.customer_name} onChange={(value) => set("customer_name", value)} required /><Field label="Email PIC" type="email" value={draft.customer_email} onChange={(value) => set("customer_email", value)} /><Field label="Telepon / WhatsApp" value={draft.customer_phone} onChange={(value) => set("customer_phone", value)} /></div><Area label="Alamat customer" value={draft.customer_address} onChange={(value) => set("customer_address", value)} rows={3} /></section>
      <section className="admin-quote-form-section"><div className="admin-editor-section-title"><div><h3>Item tagihan</h3><p>Gunakan satu item per layanan atau termin.</p></div><button className="admin-button-quiet" type="button" onClick={() => set("items", [...draft.items, emptyItem()])}>+ Tambah item</button></div><div className="admin-quotation-items">{draft.items.map((item, index) => <article key={index}><div className="admin-quotation-item-number">{String(index + 1).padStart(2, "0")}</div><div className="admin-quotation-item-fields"><Field label="Nama layanan" value={item.name} onChange={(value) => updateItem(index, "name", value)} required /><Area label="Deskripsi" value={item.description} onChange={(value) => updateItem(index, "description", value)} rows={3} /><div className="admin-form-grid admin-form-grid-3"><Field label="Qty" type="number" value={item.quantity} onChange={(value) => updateItem(index, "quantity", Number(value))} required /><Field label="Satuan" value={item.unit} onChange={(value) => updateItem(index, "unit", value)} required /><Field label="Harga satuan" type="number" value={item.unitPrice} onChange={(value) => updateItem(index, "unitPrice", Number(value))} required /></div></div><div className="admin-quotation-item-total"><span>Jumlah</span><strong>{formatRupiah(item.quantity * item.unitPrice)}</strong>{draft.items.length > 1 && <button type="button" className="danger" onClick={() => set("items", draft.items.filter((_, itemIndex) => itemIndex !== index))}>Hapus</button>}</div></article>)}</div><div className="admin-quotation-totals"><div><span>Subtotal</span><strong>{formatRupiah(subtotal)}</strong></div><label><span>Diskon</span><input type="number" min="0" max={subtotal} value={draft.discount_amount} onChange={(event) => set("discount_amount", Number(event.target.value))} /></label><div className="grand"><span>Total invoice</span><strong>{formatRupiah(total)}</strong></div><small>PPN tidak dikenakan karena RETECH saat ini Non-PKP.</small></div></section>
      <section className="admin-quote-form-section"><div className="admin-form-grid"><label className="admin-field"><span>Rekening pembayaran</span><select value={draft.payment_account_id || ""} onChange={(event) => set("payment_account_id", event.target.value)} required><option value="">Pilih rekening</option>{accounts.filter((account) => account.is_active || account.id === draft.payment_account_id).map((account) => <option value={account.id} key={account.id}>{account.label} - {account.bank_name} - {account.account_number}</option>)}</select></label><Area label="Syarat pembayaran" value={draft.payment_terms} onChange={(value) => set("payment_terms", value)} /></div><Area label="Catatan invoice" value={draft.notes} onChange={(value) => set("notes", value)} rows={5} /></section>
      {error && <p className="admin-form-message" role="alert">{error}</p>}<footer><button type="button" className="admin-button-quiet" onClick={onClose}>Batal</button><button className="admin-save-button" disabled={saving}>{saving ? "Menyimpan…" : isNew ? "Buat invoice" : "Simpan perubahan"}</button></footer>
    </form>
  </section></div>;
}

export function InvoicePanel() {
  const [records, setRecords] = useState<Invoice[]>([]); const [accounts, setAccounts] = useState<PaymentAccount[]>([]); const [quotations, setQuotations] = useState<Quotation[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<Invoice | null | undefined>(undefined); const [refreshKey, setRefreshKey] = useState(0);
  useEffect(() => { let cancelled = false; Promise.all([fetch("/api/admin/business/invoices"), fetch("/api/admin/business/payment-accounts"), fetch("/api/admin/business/quotations")]).then(async ([invoiceResponse, accountResponse, quoteResponse]) => {
    const [invoiceResult, accountResult, quoteResult] = await Promise.all([invoiceResponse.json(), accountResponse.json(), quoteResponse.json()]);
    if (!invoiceResponse.ok) throw new Error(invoiceResult.error || "Invoice gagal dimuat."); if (!accountResponse.ok) throw new Error(accountResult.error || "Rekening gagal dimuat."); if (!quoteResponse.ok) throw new Error(quoteResult.error || "Quotation gagal dimuat.");
    if (!cancelled) { setRecords((invoiceResult.records || []).map(coerce)); setAccounts(accountResult.records || []); setQuotations(quoteResult.records || []); }
  }).catch((loadError) => { if (!cancelled) setError(loadError instanceof Error ? loadError.message : "Data invoice gagal dimuat."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [refreshKey]);
  const stats = useMemo(() => ({ open: records.filter((record) => ["draft", "sent", "overdue"].includes(record.status)).length, partial: records.filter((record) => record.status === "partially_paid").length, paid: records.filter((record) => record.status === "paid").length }), [records]);
  function refresh() { setEditing(undefined); setLoading(true); setError(""); setRefreshKey((value) => value + 1); }
  async function remove(record: Invoice) { if (!window.confirm(`Hapus ${record.invoice_number}? Invoice yang punya pembayaran tidak dapat dihapus.`)) return; const response = await fetch(`/api/admin/business/invoices/${record.id}`, { method: "DELETE" }); const result = await response.json() as { error?: string }; if (!response.ok) { setError(result.error || "Invoice belum dapat dihapus."); return; } refresh(); }
  return <div className="admin-content admin-quotation-content"><section className="admin-stats admin-mail-stats"><article><span>Total invoice</span><strong>{records.length}</strong></article><article><span>Open</span><strong>{stats.open}</strong></article><article><span>Partial</span><strong>{stats.partial}</strong></article><article><span>Paid</span><strong>{stats.paid}</strong></article></section>
    <div className="admin-list-header"><div><h2>Invoices</h2><p>Buat invoice Non-PKP, pilih rekening penerimaan, lalu preview atau download PDF resmi.</p></div><button className="admin-primary-button" disabled={!accounts.some((account) => account.is_active)} onClick={() => setEditing(null)}>+ Buat invoice</button></div>
    <div className="admin-quotation-guidance"><div><strong>Invoice workflow</strong><p>Accepted quotation → draft invoice → review PDF → sent → record payment → paid.</p></div><span>NON-PKP</span></div>
    {error && <p className="admin-form-message" role="alert">{error}</p>}{!accounts.some((account) => account.is_active) && <p className="admin-form-message">Aktifkan minimal satu rekening di menu Payments sebelum membuat invoice.</p>}
    {loading ? <div className="admin-loading">Memuat invoice…</div> : records.length === 0 ? <div className="admin-empty-state"><strong>Belum ada invoice</strong><p>Buat invoice dari quotation yang telah disetujui.</p></div> : <div className="admin-quotation-list">{records.map((record) => <article key={record.id}><div className="admin-quotation-number"><span>{labels[record.status]}</span><strong>{record.invoice_number}</strong><small>{record.issue_date} - jatuh tempo {record.due_date}</small></div><div><h3>{record.customer_company}</h3><p>{record.subject}</p><small>{record.payment_account_snapshot.bank_name} · {record.payment_account_snapshot.account_number}</small></div><div className="admin-quotation-value"><span>Total</span><strong>{formatRupiah(invoiceTotal(record))}</strong><small>{record.items.length} item</small></div><div className="admin-record-actions admin-quotation-actions"><a href={`/api/admin/business/invoices/${record.id}/pdf`} target="_blank" rel="noreferrer">Preview</a><a href={`/api/admin/business/invoices/${record.id}/pdf?download=1`}>Download</a><button onClick={() => setEditing(record)}>Edit</button><button className="danger" onClick={() => void remove(record)}>Hapus</button></div></article>)}</div>}
    {editing !== undefined && <InvoiceEditor invoice={editing} accounts={accounts} quotations={quotations} onClose={() => setEditing(undefined)} onSaved={refresh} />}
  </div>;
}
