"use client";

import { FormEvent, useEffect, useState } from "react";
import { type Customer, type Product } from "@/lib/business-documents";
import { formatRupiah } from "@/lib/quotations";

function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string | number; onChange: (value:string) => void; type?: string; required?: boolean }) { return <label className="admin-field"><span>{label}</span><input type={type} value={value} required={required} onChange={(event) => onChange(event.target.value)} /></label>; }
function Area({ label, value, onChange }: { label:string; value:string; onChange:(value:string)=>void }) { return <label className="admin-field admin-field-wide"><span>{label}</span><textarea rows={4} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }

function CustomerEditor({ record, close, saved }: { record: Customer | null; close:()=>void; saved:()=>void }) { const [draft,setDraft]=useState<Omit<Customer,"id">>(record ? { ...record } : { company_name:"",contact_name:"",email:"",phone:"",address:"",notes:"",is_active:true }); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const set=<K extends keyof typeof draft>(key:K,value:(typeof draft)[K])=>setDraft((current)=>({...current,[key]:value})); async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");const response=await fetch(record?`/api/admin/business/customers/${record.id}`:"/api/admin/business/customers",{method:record?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const result=await response.json();if(!response.ok){setError(result.error||"Customer belum dapat disimpan.");setSaving(false);return;}saved();} return <div className="admin-modal-backdrop"><section className="admin-modal admin-business-modal"><header><div><span className="admin-kicker">CUSTOMER / {record?"UPDATE":"CREATE"}</span><h2>{record?record.company_name:"Tambah customer"}</h2></div><button onClick={close}>×</button></header><form onSubmit={submit}><div className="admin-form-grid"><Field label="Nama perusahaan" value={draft.company_name} onChange={(v)=>set("company_name",v)} required/><Field label="Nama PIC" value={draft.contact_name} onChange={(v)=>set("contact_name",v)} required/><Field label="Email" type="email" value={draft.email} onChange={(v)=>set("email",v)}/><Field label="Telepon / WA" value={draft.phone} onChange={(v)=>set("phone",v)}/></div><Area label="Alamat" value={draft.address} onChange={(v)=>set("address",v)}/><Area label="Catatan internal" value={draft.notes} onChange={(v)=>set("notes",v)}/><div className="admin-editor-options"><label><input type="checkbox" checked={draft.is_active} onChange={(e)=>set("is_active",e.target.checked)}/> Aktif</label></div>{error&&<p className="admin-form-message">{error}</p>}<footer><button type="button" className="admin-button-quiet" onClick={close}>Batal</button><button className="admin-save-button" disabled={saving}>Simpan customer</button></footer></form></section></div>; }

export function CustomerPanel(){const [records,setRecords]=useState<Customer[]>([]);const [editing,setEditing]=useState<Customer|null|undefined>();const [error,setError]=useState("");const [key,setKey]=useState(0);useEffect(()=>{fetch("/api/admin/business/customers").then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);setRecords(x.records||[])}).catch(e=>setError(e.message))},[key]);const refresh=()=>{setEditing(undefined);setKey(k=>k+1)};async function remove(record:Customer){if(!confirm(`Hapus ${record.company_name}?`))return;const r=await fetch(`/api/admin/business/customers/${record.id}`,{method:"DELETE"});if(!r.ok){setError((await r.json()).error);return;}refresh();}return <div className="admin-content"><div className="admin-list-header"><div><h2>Customer master</h2><p>Satu sumber data PIC untuk quotation dan invoice.</p></div><button className="admin-primary-button" onClick={()=>setEditing(null)}>+ Tambah customer</button></div>{error&&<p className="admin-form-message">{error}</p>}<div className="admin-payment-list">{records.map(r=><article key={r.id}><div><span>{r.is_active?"ACTIVE":"INACTIVE"}</span><strong>{r.company_name}</strong><small>{r.contact_name} · {r.email||r.phone||"Tanpa kontak"}</small></div><div className="admin-record-actions"><button onClick={()=>setEditing(r)}>Edit</button><button className="danger" onClick={()=>void remove(r)}>Hapus</button></div></article>)}</div>{editing!==undefined&&<CustomerEditor record={editing} close={()=>setEditing(undefined)} saved={refresh}/>}</div>}

function ProductEditor({record,close,saved}:{record:Product|null;close:()=>void;saved:()=>void}){const [draft,setDraft]=useState<Omit<Product,"id">>(record?{...record}:{code:"",name:"",category:"Service",description:"",unit:"paket",unit_price:0,is_active:true});const [error,setError]=useState("");const set=<K extends keyof typeof draft>(key:K,value:(typeof draft)[K])=>setDraft(c=>({...c,[key]:value}));async function submit(e:FormEvent){e.preventDefault();const r=await fetch(record?`/api/admin/business/products/${record.id}`:"/api/admin/business/products",{method:record?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const x=await r.json();if(!r.ok){setError(x.error);return;}saved();}return <div className="admin-modal-backdrop"><section className="admin-modal admin-business-modal"><header><div><span className="admin-kicker">PRODUCT / {record?"UPDATE":"CREATE"}</span><h2>{record?record.name:"Tambah produk/layanan"}</h2></div><button onClick={close}>×</button></header><form onSubmit={submit}><div className="admin-form-grid"><Field label="Kode unik" value={draft.code} onChange={v=>set("code",v)} required/><Field label="Nama" value={draft.name} onChange={v=>set("name",v)} required/><Field label="Kategori" value={draft.category} onChange={v=>set("category",v)} required/><Field label="Satuan" value={draft.unit} onChange={v=>set("unit",v)} required/><Field label="Harga standar" type="number" value={draft.unit_price} onChange={v=>set("unit_price",Number(v))} required/></div><Area label="Deskripsi standar" value={draft.description} onChange={v=>set("description",v)}/><div className="admin-editor-options"><label><input type="checkbox" checked={draft.is_active} onChange={e=>set("is_active",e.target.checked)}/> Aktif</label></div>{error&&<p className="admin-form-message">{error}</p>}<footer><button type="button" className="admin-button-quiet" onClick={close}>Batal</button><button className="admin-save-button">Simpan produk/layanan</button></footer></form></section></div>}

export function ProductPanel(){const [records,setRecords]=useState<Product[]>([]);const [editing,setEditing]=useState<Product|null|undefined>();const [error,setError]=useState("");const [key,setKey]=useState(0);useEffect(()=>{fetch("/api/admin/business/products").then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);setRecords((x.records||[]).map((p:Product)=>({...p,unit_price:Number(p.unit_price)})));}).catch(e=>setError(e.message));},[key]);const refresh=()=>{setEditing(undefined);setKey(k=>k+1)};async function remove(record:Product){if(!confirm(`Hapus ${record.name}?`))return;const r=await fetch(`/api/admin/business/products/${record.id}`,{method:"DELETE"});if(!r.ok){setError((await r.json()).error);return;}refresh();}return <div className="admin-content"><div className="admin-list-header"><div><h2>Products & Services</h2><p>Price book internal untuk mempercepat pembuatan quotation dan invoice.</p></div><button className="admin-primary-button" onClick={()=>setEditing(null)}>+ Tambah layanan</button></div>{error&&<p className="admin-form-message">{error}</p>}<div className="admin-payment-list">{records.map(r=><article key={r.id}><div><span>{r.code} · {r.category}</span><strong>{r.name}</strong><small>{r.description||`${r.unit}`}</small></div><div><strong>{formatRupiah(r.unit_price)}</strong><small>per {r.unit}</small></div><div className="admin-record-actions"><button onClick={()=>setEditing(r)}>Edit</button><button className="danger" onClick={()=>void remove(r)}>Hapus</button></div></article>)}</div>{editing!==undefined&&<ProductEditor record={editing} close={()=>setEditing(undefined)} saved={refresh}/>}</div>}
