"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { paymentStatuses, type Invoice, type Payment, type PaymentAccount, type PaymentAccountInput, type PaymentInput } from "@/lib/business-documents";
import { formatRupiah } from "@/lib/quotations";

function isoDate() { return new Date().toISOString().slice(0, 10); }
function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="admin-field"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} /></label>; }
function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="admin-field admin-field-wide"><span>{label}</span><textarea value={value} onChange={(event) => onChange(event.target.value)} rows={4} /></label>; }

function AccountEditor({ account, onClose, onSaved }: { account: PaymentAccount | null; onClose: () => void; onSaved: () => void }) {
  const isNew = account == null;
  const [draft, setDraft] = useState<PaymentAccountInput>(() => account ? { label: account.label, bank_name: account.bank_name, account_name: account.account_name, account_number: account.account_number, branch: account.branch || "", currency: account.currency || "IDR", instructions: account.instructions || "", is_active: account.is_active, is_default: account.is_default } : { label: "", bank_name: "", account_name: "PT RETECH DIGITAL SOLUTION", account_number: "", branch: "", currency: "IDR", instructions: "Cantumkan nomor invoice pada berita transfer.", is_active: true, is_default: false });
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const set = <K extends keyof PaymentAccountInput>(key: K, value: PaymentAccountInput[K]) => setDraft((current) => ({ ...current, [key]: value }));
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(isNew ? "/api/admin/business/payment-accounts" : `/api/admin/business/payment-accounts/${account.id}`, { method: isNew ? "POST" : "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error || "Rekening belum dapat disimpan."); onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Rekening belum dapat disimpan."); setSaving(false); } }
  return <div className="admin-modal-backdrop"><section className="admin-modal admin-business-modal" role="dialog" aria-modal="true"><header><div><span className="admin-kicker">PAYMENTS / ACCOUNT / {isNew ? "CREATE" : "UPDATE"}</span><h2>{isNew ? "Tambah rekening" : account.label}</h2></div><button type="button" onClick={onClose}>×</button></header><form onSubmit={save}><div className="admin-form-grid"><Field label="Label rekening" value={draft.label} onChange={(value) => set("label", value)} required /><Field label="Nama bank" value={draft.bank_name} onChange={(value) => set("bank_name", value)} required /><Field label="Nama rekening" value={draft.account_name} onChange={(value) => set("account_name", value)} required /><Field label="Nomor rekening" value={draft.account_number} onChange={(value) => set("account_number", value)} required /><Field label="Cabang" value={draft.branch} onChange={(value) => set("branch", value)} /><Field label="Mata uang" value={draft.currency} onChange={(value) => set("currency", value)} required /></div><Area label="Instruksi pembayaran" value={draft.instructions} onChange={(value) => set("instructions", value)} /><div className="admin-editor-options"><label><input type="checkbox" checked={draft.is_active} onChange={(event) => set("is_active", event.target.checked)} /> Aktif</label><label><input type="checkbox" checked={draft.is_default} onChange={(event) => set("is_default", event.target.checked)} /> Jadikan rekening default</label></div>{error && <p className="admin-form-message">{error}</p>}<footer><button type="button" className="admin-button-quiet" onClick={onClose}>Batal</button><button className="admin-save-button" disabled={saving}>{saving ? "Menyimpan…" : "Simpan rekening"}</button></footer></form></section></div>;
}

function PaymentEditor({ payment, invoices, accounts, onClose, onSaved }: { payment: Payment | null; invoices: Invoice[]; accounts: PaymentAccount[]; onClose: () => void; onSaved: () => void }) {
  const isNew = payment == null; const defaultInvoice = invoices.find((invoice) => !["paid", "cancelled"].includes(invoice.status)); const defaultAccount = accounts.find((account) => account.is_default && account.is_active) || accounts.find((account) => account.is_active);
  const [draft, setDraft] = useState<PaymentInput>(() => payment ? { invoice_id: payment.invoice_id, payment_account_id: payment.payment_account_id, payment_date: payment.payment_date, amount: Number(payment.amount), method: payment.method, reference_number: payment.reference_number || "", status: payment.status, notes: payment.notes || "" } : { invoice_id: defaultInvoice?.id || "", payment_account_id: defaultAccount?.id || "", payment_date: isoDate(), amount: 0, method: "Bank Transfer", reference_number: "", status: "confirmed", notes: "" });
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const set = <K extends keyof PaymentInput>(key: K, value: PaymentInput[K]) => setDraft((current) => ({ ...current, [key]: value }));
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(isNew ? "/api/admin/business/payments" : `/api/admin/business/payments/${payment.id}`, { method: isNew ? "POST" : "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error || "Pembayaran belum dapat disimpan."); onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Pembayaran belum dapat disimpan."); setSaving(false); } }
  return <div className="admin-modal-backdrop"><section className="admin-modal admin-business-modal" role="dialog" aria-modal="true"><header><div><span className="admin-kicker">PAYMENTS / TRANSACTION / {isNew ? "CREATE" : "UPDATE"}</span><h2>{isNew ? "Catat pembayaran" : "Edit pembayaran"}</h2></div><button type="button" onClick={onClose}>×</button></header><form onSubmit={save}><div className="admin-form-grid"><label className="admin-field"><span>Invoice</span><select value={draft.invoice_id} onChange={(event) => set("invoice_id", event.target.value)} required><option value="">Pilih invoice</option>{invoices.map((invoice) => <option value={invoice.id} key={invoice.id}>{invoice.invoice_number} - {invoice.customer_company}</option>)}</select></label><label className="admin-field"><span>Rekening penerima</span><select value={draft.payment_account_id} onChange={(event) => set("payment_account_id", event.target.value)} required><option value="">Pilih rekening</option>{accounts.filter((account) => account.is_active || account.id === draft.payment_account_id).map((account) => <option value={account.id} key={account.id}>{account.label} - {account.account_number}</option>)}</select></label><Field label="Tanggal pembayaran" type="date" value={draft.payment_date} onChange={(value) => set("payment_date", value)} required /><Field label="Nominal" type="number" value={draft.amount} onChange={(value) => set("amount", Number(value))} required /><Field label="Metode" value={draft.method} onChange={(value) => set("method", value)} required /><Field label="Nomor referensi" value={draft.reference_number} onChange={(value) => set("reference_number", value)} /><label className="admin-field"><span>Status</span><select value={draft.status} onChange={(event) => set("status", event.target.value as PaymentInput["status"])}>{paymentStatuses.map((status) => <option value={status} key={status}>{status}</option>)}</select></label></div><Area label="Catatan" value={draft.notes} onChange={(value) => set("notes", value)} />{error && <p className="admin-form-message">{error}</p>}<footer><button type="button" className="admin-button-quiet" onClick={onClose}>Batal</button><button className="admin-save-button" disabled={saving}>{saving ? "Menyimpan…" : "Simpan pembayaran"}</button></footer></form></section></div>;
}

export function PaymentsPanel() {
  const [accounts, setAccounts] = useState<PaymentAccount[]>([]); const [invoices, setInvoices] = useState<Invoice[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [accountEditor, setAccountEditor] = useState<PaymentAccount | null | undefined>(undefined); const [paymentEditor, setPaymentEditor] = useState<Payment | null | undefined>(undefined); const [refreshKey, setRefreshKey] = useState(0);
  useEffect(() => { let cancelled = false; Promise.all([fetch("/api/admin/business/payment-accounts"), fetch("/api/admin/business/invoices"), fetch("/api/admin/business/payments")]).then(async (responses) => { const results = await Promise.all(responses.map((response) => response.json())); const failed = responses.findIndex((response) => !response.ok); if (failed >= 0) throw new Error(results[failed].error || "Data pembayaran gagal dimuat."); if (!cancelled) { setAccounts(results[0].records || []); setInvoices(results[1].records || []); setPayments((results[2].records || []).map((payment: Payment) => ({ ...payment, amount: Number(payment.amount) }))); } }).catch((loadError) => { if (!cancelled) setError(loadError instanceof Error ? loadError.message : "Data pembayaran gagal dimuat."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [refreshKey]);
  const confirmedTotal = useMemo(() => payments.filter((payment) => payment.status === "confirmed").reduce((sum, payment) => sum + Number(payment.amount), 0), [payments]);
  function refresh() { setAccountEditor(undefined); setPaymentEditor(undefined); setLoading(true); setError(""); setRefreshKey((value) => value + 1); }
  async function removeAccount(account: PaymentAccount) { if (!window.confirm(`Hapus rekening ${account.label}? Rekening yang sudah dipakai tidak dapat dihapus.`)) return; const response = await fetch(`/api/admin/business/payment-accounts/${account.id}`, { method: "DELETE" }); const result = await response.json() as { error?: string }; if (!response.ok) { setError(result.error || "Rekening belum dapat dihapus."); return; } refresh(); }
  async function removePayment(payment: Payment) { if (!window.confirm("Hapus catatan pembayaran ini? Status invoice akan dihitung ulang.")) return; const response = await fetch(`/api/admin/business/payments/${payment.id}`, { method: "DELETE" }); const result = await response.json() as { error?: string }; if (!response.ok) { setError(result.error || "Pembayaran belum dapat dihapus."); return; } refresh(); }
  const invoiceLabel = (id: string) => { const invoice = invoices.find((record) => record.id === id); return invoice ? `${invoice.invoice_number} · ${invoice.customer_company}` : "Invoice tidak ditemukan"; };
  const accountLabel = (id: string) => accounts.find((account) => account.id === id)?.label || "Rekening tidak ditemukan";
  return <div className="admin-content admin-payment-content"><section className="admin-stats admin-mail-stats"><article><span>Rekening aktif</span><strong>{accounts.filter((account) => account.is_active).length}</strong></article><article><span>Transaksi</span><strong>{payments.length}</strong></article><article><span>Confirmed</span><strong>{payments.filter((payment) => payment.status === "confirmed").length}</strong></article><article><span>Dana diterima</span><strong>{formatRupiah(confirmedTotal)}</strong></article></section>
    {error && <p className="admin-form-message">{error}</p>}{loading ? <div className="admin-loading">Memuat pembayaran…</div> : <><section className="admin-business-section"><div className="admin-list-header"><div><h2>Rekening penerimaan</h2><p>Rekening aktif dapat dipilih saat membuat invoice. Invoice menyimpan snapshot rekening.</p></div><button className="admin-primary-button" onClick={() => setAccountEditor(null)}>+ Tambah rekening</button></div><div className="admin-account-grid">{accounts.map((account) => <article key={account.id}><div><span>{account.is_default ? "DEFAULT" : account.is_active ? "ACTIVE" : "INACTIVE"}</span><h3>{account.label}</h3><p>{account.bank_name}</p></div><strong>{account.account_number}</strong><small>a.n. {account.account_name}</small>{account.branch && <small>Cabang {account.branch}</small>}<div className="admin-record-actions"><button onClick={() => setAccountEditor(account)}>Edit</button><button className="danger" onClick={() => void removeAccount(account)}>Hapus</button></div></article>)}</div></section>
      <section className="admin-business-section"><div className="admin-list-header"><div><h2>Transaksi pembayaran</h2><p>Catat pembayaran masuk; status invoice otomatis menjadi partially paid atau paid.</p></div><button className="admin-primary-button" disabled={!invoices.length || !accounts.some((account) => account.is_active)} onClick={() => setPaymentEditor(null)}>+ Catat pembayaran</button></div>{payments.length === 0 ? <div className="admin-empty-state"><strong>Belum ada pembayaran</strong><p>Transaksi pertama akan tampil di sini.</p></div> : <div className="admin-payment-list">{payments.map((payment) => <article key={payment.id}><div><span>{payment.status}</span><strong>{invoiceLabel(payment.invoice_id)}</strong><small>{payment.payment_date} · {accountLabel(payment.payment_account_id)}</small></div><div><strong>{formatRupiah(payment.amount)}</strong><small>{payment.reference_number || payment.method}</small></div><div className="admin-record-actions"><button onClick={() => setPaymentEditor(payment)}>Edit</button><button className="danger" onClick={() => void removePayment(payment)}>Hapus</button></div></article>)}</div>}</section></>}
    {accountEditor !== undefined && <AccountEditor account={accountEditor} onClose={() => setAccountEditor(undefined)} onSaved={refresh} />}{paymentEditor !== undefined && <PaymentEditor payment={paymentEditor} invoices={invoices} accounts={accounts} onClose={() => setPaymentEditor(undefined)} onSaved={refresh} />}
  </div>;
}
