"use client";

import { FormEvent, useEffect, useState } from "react";
import { formatRupiah } from "@/lib/quotations";
import { SAAS_PRODUCTS, SUBSCRIPTION_STATUSES, TENANT_STATUSES, type SaasSubscription, type SaasTenant } from "@/lib/saas";

function Field({ label, value, onChange, type = "text", required = false }: { label:string; value:string|number; onChange:(value:string)=>void; type?:string; required?:boolean }) { return <label className="admin-field"><span>{label}</span><input type={type} value={value} required={required} onChange={(event)=>onChange(event.target.value)} /></label>; }
function Select({ label, value, options, onChange }: { label:string; value:string; options:Array<{value:string;label:string}>; onChange:(value:string)=>void }) { return <label className="admin-field"><span>{label}</span><select value={value} onChange={(event)=>onChange(event.target.value)}>{options.map((option)=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label>; }
const productOptions = SAAS_PRODUCTS.map((value)=>({value,label:value === "qr-order-pos" ? "QR Order & POS" : "Attendance"}));

function TenantEditor({ record, close, saved }: { record:SaasTenant|null; close:()=>void; saved:()=>void }) {
  const [draft,setDraft]=useState(record ? {...record} : { slug:"",display_name:"",product:"qr-order-pos",status:"trialing",primary_contact_email:"",primary_contact_phone:"",customer_id:null,settings:{} } as Omit<SaasTenant,"id">);
  const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  const set=(key:string,value:unknown)=>setDraft((current)=>({...current,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");const response=await fetch(record?`/api/admin/saas/tenants/${record.id}`:"/api/admin/saas/tenants",{method:record?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const result=await response.json();if(!response.ok){setError(result.error||"Tenant belum dapat disimpan.");setSaving(false);return;}saved();}
  return <div className="admin-modal-backdrop"><section className="admin-modal admin-business-modal"><header><div><span className="admin-kicker">SAAS / TENANT / {record?"UPDATE":"CREATE"}</span><h2>{record?record.display_name:"Tambah tenant"}</h2></div><button onClick={close}>×</button></header><form onSubmit={submit}><div className="admin-form-grid"><Field label="Nama workspace" value={draft.display_name} onChange={(value)=>set("display_name",value)} required/><Field label="Slug tenant" value={draft.slug} onChange={(value)=>set("slug",value.toLowerCase().replace(/[^a-z0-9-]+/g,"-"))} required/><Select label="Produk" value={draft.product} options={productOptions} onChange={(value)=>set("product",value)}/><Select label="Status" value={draft.status} options={TENANT_STATUSES.map((value)=>({value,label:value}))} onChange={(value)=>set("status",value)}/><Field label="Email PIC" type="email" value={draft.primary_contact_email||""} onChange={(value)=>set("primary_contact_email",value)}/><Field label="Telepon / WA PIC" value={draft.primary_contact_phone||""} onChange={(value)=>set("primary_contact_phone",value)}/></div>{error&&<p className="admin-form-message">{error}</p>}<footer><button type="button" className="admin-button-quiet" onClick={close}>Batal</button><button className="admin-save-button" disabled={saving}>{saving?"Menyimpan…":"Simpan tenant"}</button></footer></form></section></div>;
}
export function TenantPanel(){
  const [records,setRecords]=useState<SaasTenant[]>([]);const [editing,setEditing]=useState<SaasTenant|null|undefined>();const [error,setError]=useState("");const [key,setKey]=useState(0);
  useEffect(()=>{fetch("/api/admin/saas/tenants").then(async(response)=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setRecords(result.records||[]);}).catch((loadError)=>setError(loadError.message));},[key]);
  const refresh=()=>{setEditing(undefined);setKey((value)=>value+1);};
  async function remove(record:SaasTenant){if(!confirm(`Hapus tenant ${record.display_name}?`))return;const response=await fetch(`/api/admin/saas/tenants/${record.id}`,{method:"DELETE"});if(!response.ok){setError((await response.json()).error);return;}refresh();}
  return <div className="admin-content"><section className="admin-stats"><article><span>Total tenant</span><strong>{records.length}</strong></article><article><span>Active</span><strong>{records.filter((record)=>record.status==="active").length}</strong></article><article><span>Trial</span><strong>{records.filter((record)=>record.status==="trialing").length}</strong></article></section><div className="admin-list-header"><div><h2>Tenant management</h2><p>Workspace customer terpisah untuk QR Order & POS dan Attendance.</p></div><button className="admin-primary-button" onClick={()=>setEditing(null)}>+ Tambah tenant</button></div>{error&&<p className="admin-form-message">{error}</p>}<div className="admin-payment-list">{records.map((record)=><article key={record.id}><div><span>{record.product} · {record.status}</span><strong>{record.display_name}</strong><small>{record.slug} · {record.primary_contact_email||record.primary_contact_phone||"Belum ada PIC"}</small></div><div className="admin-record-actions"><button onClick={()=>setEditing(record)}>Edit</button><button className="danger" onClick={()=>void remove(record)}>Hapus</button></div></article>)}</div>{editing!==undefined&&<TenantEditor record={editing} close={()=>setEditing(undefined)} saved={refresh}/>}</div>;
}

function localDate(value:string|null){return value?new Date(value).toISOString().slice(0,16):"";}

function SubscriptionEditor({record,tenants,close,saved}:{record:SaasSubscription|null;tenants:SaasTenant[];close:()=>void;saved:()=>void}){
  const [draft,setDraft]=useState(record?{...record}:{tenant_id:tenants[0]?.id||"",product:tenants[0]?.product||"qr-order-pos",plan_code:"",billing_cycle:"monthly",amount:0,currency:"IDR",status:"trialing",seat_quantity:1,current_period_start:null,current_period_end:null,grace_until:null,auto_renew:true,payment_provider:null,external_reference:null,last_payment_at:null,entitlements:{}} as Omit<SaasSubscription,"id">);
  const [error,setError]=useState("");const [saving,setSaving]=useState(false);const set=(key:string,value:unknown)=>setDraft((current)=>({...current,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");const response=await fetch(record?`/api/admin/saas/subscriptions/${record.id}`:"/api/admin/saas/subscriptions",{method:record?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const result=await response.json();if(!response.ok){setError(result.error||"Subscription belum dapat disimpan.");setSaving(false);return;}saved();}
  return <div className="admin-modal-backdrop"><section className="admin-modal admin-business-modal"><header><div><span className="admin-kicker">SAAS / SUBSCRIPTION / {record?"UPDATE":"CREATE"}</span><h2>{record?record.plan_code:"Tambah subscription"}</h2></div><button onClick={close}>×</button></header><form onSubmit={submit}><div className="admin-form-grid"><Select label="Tenant" value={draft.tenant_id} options={tenants.map((tenant)=>({value:tenant.id,label:`${tenant.display_name} · ${tenant.product}`}))} onChange={(value)=>{set("tenant_id",value);const tenant=tenants.find((item)=>item.id===value);if(tenant)set("product",tenant.product);}}/><Select label="Produk" value={draft.product} options={productOptions} onChange={(value)=>set("product",value)}/><Field label="Kode paket" value={draft.plan_code} onChange={(value)=>set("plan_code",value.toLowerCase().replace(/[^a-z0-9-]+/g,"-"))} required/><Select label="Billing cycle" value={draft.billing_cycle} options={[{value:"monthly",label:"Bulanan"},{value:"annual",label:"Tahunan"}]} onChange={(value)=>set("billing_cycle",value)}/><Field label="Nilai billing" type="number" value={draft.amount} onChange={(value)=>set("amount",Number(value))} required/><Field label="Seat / outlet" type="number" value={draft.seat_quantity} onChange={(value)=>set("seat_quantity",Number(value))} required/><Select label="Status" value={draft.status} options={SUBSCRIPTION_STATUSES.map((value)=>({value,label:value}))} onChange={(value)=>set("status",value)}/><Field label="Provider pembayaran" value={draft.payment_provider||""} onChange={(value)=>set("payment_provider",value)}/><Field label="Awal periode" type="datetime-local" value={localDate(draft.current_period_start)} onChange={(value)=>set("current_period_start",value||null)}/><Field label="Akhir periode" type="datetime-local" value={localDate(draft.current_period_end)} onChange={(value)=>set("current_period_end",value||null)}/><Field label="Grace until" type="datetime-local" value={localDate(draft.grace_until)} onChange={(value)=>set("grace_until",value||null)}/><Field label="Referensi provider" value={draft.external_reference||""} onChange={(value)=>set("external_reference",value)}/></div><div className="admin-editor-options"><label><input type="checkbox" checked={draft.auto_renew} onChange={(event)=>set("auto_renew",event.target.checked)}/> Auto renew</label></div>{error&&<p className="admin-form-message">{error}</p>}<footer><button type="button" className="admin-button-quiet" onClick={close}>Batal</button><button className="admin-save-button" disabled={saving}>{saving?"Menyimpan…":"Simpan subscription"}</button></footer></form></section></div>;
}

type SubscriptionRecord=SaasSubscription&{saas_tenants?:{display_name?:string;slug?:string}|null};
export function SubscriptionPanel(){
  const [records,setRecords]=useState<SubscriptionRecord[]>([]);const [tenants,setTenants]=useState<SaasTenant[]>([]);const [editing,setEditing]=useState<SaasSubscription|null|undefined>();const [error,setError]=useState("");const [key,setKey]=useState(0);
  useEffect(()=>{Promise.all([fetch("/api/admin/saas/subscriptions"),fetch("/api/admin/saas/tenants")]).then(async([subscriptionResponse,tenantResponse])=>{const subscriptions=await subscriptionResponse.json();const tenantResult=await tenantResponse.json();if(!subscriptionResponse.ok)throw new Error(subscriptions.error);if(!tenantResponse.ok)throw new Error(tenantResult.error);setRecords((subscriptions.records||[]).map((record:SubscriptionRecord)=>({...record,amount:Number(record.amount)})));setTenants(tenantResult.records||[]);}).catch((loadError)=>setError(loadError.message));},[key]);
  const refresh=()=>{setEditing(undefined);setKey((value)=>value+1);};
  async function remove(record:SaasSubscription){if(!confirm(`Hapus subscription ${record.plan_code}?`))return;const response=await fetch(`/api/admin/saas/subscriptions/${record.id}`,{method:"DELETE"});if(!response.ok){setError((await response.json()).error);return;}refresh();}
  return <div className="admin-content"><section className="admin-stats"><article><span>Total subscription</span><strong>{records.length}</strong></article><article><span>Active</span><strong>{records.filter((record)=>record.status==="active").length}</strong></article><article><span>Attention</span><strong>{records.filter((record)=>["past_due","grace_period","suspended"].includes(record.status)).length}</strong></article></section><div className="admin-list-header"><div><h2>Subscription lifecycle</h2><p>Aktivasi, billing period, grace period, suspension, dan entitlement per tenant.</p></div><button className="admin-primary-button" disabled={!tenants.length} onClick={()=>setEditing(null)}>+ Tambah subscription</button></div>{error&&<p className="admin-form-message">{error}</p>}{!tenants.length&&!error&&<p className="admin-form-message">Buat tenant terlebih dahulu sebelum menambahkan subscription.</p>}<div className="admin-payment-list">{records.map((record)=><article key={record.id}><div><span>{record.product} · {record.status}</span><strong>{record.saas_tenants?.display_name||record.plan_code}</strong><small>{record.plan_code} · {record.billing_cycle} · {record.seat_quantity} seat/outlet</small></div><div><strong>{formatRupiah(record.amount)}</strong><small>{record.current_period_end?`s.d. ${new Date(record.current_period_end).toLocaleDateString("id-ID")}`:"Periode belum ditetapkan"}</small></div><div className="admin-record-actions"><button onClick={()=>setEditing(record)}>Edit</button><button className="danger" onClick={()=>void remove(record)}>Hapus</button></div></article>)}</div>{editing!==undefined&&<SubscriptionEditor record={editing} tenants={tenants} close={()=>setEditing(undefined)} saved={refresh}/>}</div>;
}
