import path from "node:path";
import { readFile } from "node:fs/promises";
import { renderToBuffer } from "@react-pdf/renderer";
import { readAdminSessionFromRequest } from "@/lib/admin-auth";
import type { Invoice, Payment } from "@/lib/business-documents";
import { ReceiptPdf } from "@/lib/receipt-pdf";
import { supabaseAdminFetch } from "@/lib/supabase-admin";
export const runtime="nodejs";
export async function GET(request:Request,context:{params:Promise<{id:string}>}){if(!readAdminSessionFromRequest(request))return Response.json({error:"Unauthorized"},{status:401});const {id}=await context.params;const paymentResponse=await supabaseAdminFetch(`/rest/v1/business_payments?select=*&id=eq.${encodeURIComponent(id)}&limit=1`);const payments=paymentResponse.ok?await paymentResponse.json() as Payment[]:[];if(!payments.length)return Response.json({error:"Pembayaran tidak ditemukan."},{status:404});const payment={...payments[0],amount:Number(payments[0].amount)};if(payment.status!=="confirmed"||!payment.receipt_number)return Response.json({error:"Kwitansi hanya tersedia untuk pembayaran confirmed."},{status:409});const invoiceResponse=await supabaseAdminFetch(`/rest/v1/business_invoices?select=*&id=eq.${encodeURIComponent(payment.invoice_id)}&limit=1`);const invoices=invoiceResponse.ok?await invoiceResponse.json() as Invoice[]:[];if(!invoices.length)return Response.json({error:"Invoice tidak ditemukan."},{status:404});const invoice={...invoices[0],discount_amount:Number(invoices[0].discount_amount||0)};const [logo,signature,stamp]=await Promise.all([readFile(path.join(process.cwd(),"public","retech-logo-transparent.png")),readFile(path.join(process.cwd(),"public","documents","retech-signature.png")),readFile(path.join(process.cwd(),"public","documents","retech-stamp-transparent.png"))]);const pdf=await renderToBuffer(<ReceiptPdf payment={payment} invoice={invoice} logoSrc={`data:image/png;base64,${logo.toString("base64")}`} signatureSrc={`data:image/png;base64,${signature.toString("base64")}`} stampSrc={`data:image/png;base64,${stamp.toString("base64")}`}/>);const disposition=new URL(request.url).searchParams.get("download")==="1"?"attachment":"inline";const filename=`RETECH-Receipt-${payment.receipt_number.replace(/[^A-Za-z0-9_-]+/g,"-")}.pdf`;return new Response(new Uint8Array(pdf),{headers:{"Content-Type":"application/pdf","Content-Disposition":`${disposition}; filename="${filename}"`,"Cache-Control":"private, no-store"}})}
