import type { Invoice } from "@/lib/business-documents";
import { recordInvoiceEmailEvent, sendInvoiceEmail } from "@/lib/invoice-mailer";
import { supabaseAdminFetch } from "@/lib/supabase-admin";

export const runtime="nodejs"; export const maxDuration=60;
function authorized(request:Request){const secret=process.env.CRON_SECRET||"";return Boolean(secret)&&request.headers.get("authorization")===`Bearer ${secret}`;}
function day(value:string){return value.slice(0,10)}
function reminderDue(invoice:Invoice,today:string){const difference=Math.round((Date.parse(`${invoice.due_date}T00:00:00Z`)-Date.parse(`${today}T00:00:00Z`))/86400000);return difference===3||difference===0||difference===-3||(difference<-3&&Math.abs(difference)%7===0);}
export async function GET(request:Request){if(!authorized(request))return Response.json({error:"Unauthorized"},{status:401});const today=new Date().toISOString().slice(0,10);const response=await supabaseAdminFetch("/rest/v1/business_invoices?select=*&reminder_enabled=eq.true&status=in.(sent,partially_paid,overdue)&order=due_date.asc");if(!response.ok)return Response.json({error:"Invoice reminders belum dapat dimuat."},{status:502});const invoices=await response.json() as Invoice[];let sent=0;const errors:string[]=[];for(const raw of invoices.slice(0,25)){const invoice={...raw,discount_amount:Number(raw.discount_amount||0)};if(!invoice.customer_email||!reminderDue(invoice,today)||(invoice.last_reminder_at&&day(invoice.last_reminder_at)===today))continue;try{const messageId=await sendInvoiceEmail(invoice,true);const now=new Date().toISOString();await supabaseAdminFetch(`/rest/v1/business_invoices?id=eq.${encodeURIComponent(invoice.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:invoice.due_date<today?"overdue":invoice.status,last_reminder_at:now,reminder_count:Number(invoice.reminder_count||0)+1,last_email_at:now,last_email_event_at:now,delivery_status:"submitted"})});await recordInvoiceEmailEvent(invoice.id,"reminder_submitted",invoice.customer_email,messageId||null,null);sent++;}catch(error){const reason=error instanceof Error?error.message:"Reminder gagal";errors.push(`${invoice.invoice_number}: ${reason}`);await recordInvoiceEmailEvent(invoice.id,"reminder_error",invoice.customer_email,null,reason);}}return Response.json({ok:true,processed:invoices.length,sent,errors});}
