import { companyContact } from "./company";
import { invoiceTotal, type Invoice } from "./business-documents";
import { formatRupiah } from "./quotations";

function escapeHtml(value: unknown) { return String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] || character); }
function dateLabel(value: string) { return new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
export function invoiceEmailSubject(invoice: Invoice, reminder = false) { return `${reminder ? "Pengingat " : ""}Invoice ${invoice.invoice_number} - ${invoice.subject}`; }
export function invoiceEmailHtml(invoice: Invoice, reminder = false) { const total = escapeHtml(formatRupiah(invoiceTotal(invoice))); return `<!doctype html><html lang="id"><body style="margin:0;background:#eef5f8;color:#071827;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:28px 12px"><tr><td align="center"><table role="presentation" width="640" cellpadding="0" cellspacing="0" style="max-width:640px;width:100%;background:#fff;border-radius:16px;overflow:hidden"><tr><td style="height:7px;background:#176fe8"></td></tr><tr><td style="padding:28px 34px;background:#071827"><img src="https://retech.id/retech-logo-transparent.png" width="118" alt="RETECH"><div style="margin-top:16px;color:#18bfee;font-size:11px;font-weight:700;letter-spacing:1.8px">BILLING & ACCOUNT RECEIVABLE</div></td></tr><tr><td style="padding:34px"><p style="font-size:16px">Yth. Bapak/Ibu <strong>${escapeHtml(invoice.customer_name)}</strong>,</p><p style="color:#587184;font-size:14px;line-height:1.7">${reminder ? "Kami mengingatkan bahwa invoice berikut masih memiliki saldo yang perlu diselesaikan." : "Bersama email ini kami lampirkan invoice resmi RETECH untuk layanan yang telah disepakati."}</p><table role="presentation" width="100%" style="background:#edf7fc;border:1px solid #c9d8e3;border-radius:12px"><tr><td style="padding:18px 20px;color:#587184;font-size:12px;line-height:2"><strong style="display:inline-block;width:130px;color:#0a2a43">Nomor invoice</strong>${escapeHtml(invoice.invoice_number)}<br><strong style="display:inline-block;width:130px;color:#0a2a43">Jatuh tempo</strong>${escapeHtml(dateLabel(invoice.due_date))}<br><strong style="display:inline-block;width:130px;color:#0a2a43">Total invoice</strong><span style="color:#176fe8;font-size:16px;font-weight:700">${total}</span></td></tr></table><p style="margin-top:24px;color:#587184;font-size:13px;line-height:1.7">Mohon cantumkan nomor invoice pada berita transfer. Jika pembayaran telah dilakukan, balas email ini dengan bukti transfer agar tim billing dapat melakukan konfirmasi.</p><p style="margin-top:30px;font-size:13px;line-height:1.7">Hormat kami,<br><strong>Billing Team - RETECH</strong><br><a href="mailto:${companyContact.billingEmail}" style="color:#176fe8">${companyContact.billingEmail}</a></p></td></tr><tr><td style="padding:20px 34px;border-top:1px solid #c9d8e3;background:#f8fbfc;color:#587184;font-size:10px;line-height:1.6"><strong style="color:#0a2a43">PT RETECH DIGITAL SOLUTION</strong><br>${escapeHtml(companyContact.address)}<br>${escapeHtml(companyContact.whatsappDisplay)} (chat only) - retech.id</td></tr><tr><td style="height:4px;background:#176fe8"></td></tr></table></td></tr></table></body></html>`; }
export function invoiceEmailText(invoice: Invoice, reminder = false) { return `Yth. Bapak/Ibu ${invoice.customer_name},\n\n${reminder ? "Pengingat pembayaran" : "Terlampir invoice resmi"} ${invoice.invoice_number} untuk ${invoice.subject}.\nJatuh tempo: ${dateLabel(invoice.due_date)}\nTotal: ${formatRupiah(invoiceTotal(invoice))}\n\nMohon cantumkan nomor invoice pada berita transfer.\n\nBilling Team - RETECH\n${companyContact.billingEmail}`; }
