import type { Locale } from "./i18n";

export type PricingSection = "development" | "support" | "hosting";
export type PricingData = { eyebrow?: string; name: string; price: string; description: string; features: string[]; recommended?: boolean };
export type PricingRecord = { id?: string; slug: string; section: PricingSection; data: PricingData; sortOrder: number };

const idRecords: PricingRecord[] = [
  { slug: "landing-page", section: "development", sortOrder: 1, data: { eyebrow: "LANDING PAGE", name: "Landing Page", price: "Rp2,5 juta", description: "Satu halaman yang fokus menghasilkan inquiry untuk promosi produk, jasa, personal brand, atau campaign digital.", features: ["Hingga 8 section", "Custom UI sesuai brand", "Modern frontend dengan Next.js/React", "Responsive & mobile-friendly", "Form inquiry dan WhatsApp CTA", "Basic SEO, deployment, dan SSL", "2x revisi dan garansi bug 30 hari"] } },
  { slug: "company-profile", section: "development", sortOrder: 2, data: { eyebrow: "DIGITAL PRESENCE", name: "Company Profile", price: "Rp4,5 juta", description: "Untuk bisnis yang membutuhkan website profesional, cepat, dan mudah ditemukan.", features: ["Hingga 7 halaman", "Modern frontend dengan Next.js/React", "Responsive & mobile-friendly", "Form kontak dan basic SEO", "Deployment dan SSL", "Garansi bug 30 hari"] } },
  { slug: "website-cms", section: "development", sortOrder: 3, data: { eyebrow: "BUSINESS SYSTEM", name: "Website + CMS", price: "Rp10 juta", description: "Website dengan area pengelolaan konten atau dashboard sesuai alur kerja bisnis.", features: ["UI sesuai brand", "CMS atau dashboard admin", "Next.js/React atau Laravel sesuai kebutuhan", "Database dan user management", "Integrasi email", "Garansi bug 60 hari"], recommended: true } },
  { slug: "web-app", section: "development", sortOrder: 4, data: { eyebrow: "CUSTOM WEB SYSTEM", name: "Web App", price: "Rp20 juta", description: "Aplikasi berbasis browser untuk menjalankan proses bisnis, workflow, dan pengolahan data custom.", features: ["Discovery dan pemetaan workflow", "Next.js/React dan Laravel/API sesuai kebutuhan", "Frontend, backend, database, dan API", "Role dan hak akses", "Dashboard dan reporting dasar", "Testing, deployment, dan handover", "Garansi bug 60 hari"] } },
  { slug: "android-app", section: "development", sortOrder: 5, data: { eyebrow: "ANDROID APPLICATION", name: "Android App", price: "Rp25 juta", description: "Aplikasi Android custom untuk kebutuhan operasional, layanan customer, atau digitalisasi proses lapangan.", features: ["Flutter atau teknologi native sesuai kebutuhan", "UI Android dan fitur inti", "Backend dan API dasar", "Testing dan file APK/AAB", "Bantuan submission Google Play", "Akun dan biaya Play Store tidak termasuk", "Garansi bug 60 hari"] } },
  { slug: "android-ios", section: "development", sortOrder: 6, data: { eyebrow: "MULTI-PLATFORM APP", name: "Android + iOS", price: "Rp50 juta", description: "Satu solusi mobile untuk Android dan iOS dengan backend serta alur pengguna yang terintegrasi.", features: ["Cross-platform modern menggunakan Flutter", "Aplikasi Android dan iOS", "Backend, database, dan API dasar", "Testing dan production build", "Bantuan submission kedua store", "Akun dan biaya store tidak termasuk", "Garansi bug 90 hari"] } },
  { slug: "server-care-basic", section: "support", sortOrder: 1, data: { name: "Server Care Basic", price: "Mulai Rp500 ribu / server / bulan", description: "Monitoring, pemeriksaan resource, SSL, dan patch terjadwal.", features: [] } },
  { slug: "server-care-pro", section: "support", sortOrder: 2, data: { name: "Server Care Pro", price: "Mulai Rp1,5 juta / server / bulan", description: "Monitoring lebih lengkap, backup check, dan bantuan insiden prioritas.", features: [] } },
  { slug: "remote-support", section: "support", sortOrder: 3, data: { name: "Remote Support", price: "Mulai Rp250 ribu / sesi", description: "Troubleshooting satu kendala melalui koneksi remote.", features: [] } },
  { slug: "server-installation", section: "support", sortOrder: 4, data: { name: "Server Installation", price: "Mulai Rp1,5 juta", description: "Instalasi dan konfigurasi Linux server berdasarkan kebutuhan.", features: [] } },
  { slug: "domain-hosting-basic", section: "hosting", sortOrder: 1, data: { name: "Domain & Hosting Basic", price: "Rp1 juta / tahun", description: "Untuk landing page atau company profile statis dengan kebutuhan trafik normal.", features: ["Domain .com maksimal Rp250 ribu", "Hosting website statis", "DNS dan konfigurasi SSL", "Deployment awal", "Monitoring uptime dasar"] } },
  { slug: "managed-cloud-hosting", section: "hosting", sortOrder: 2, data: { name: "Managed Cloud Hosting", price: "Rp3 juta / tahun", description: "Untuk website CMS atau aplikasi kecil yang membutuhkan runtime, database, dan pengelolaan server.", features: ["Cloud server sesuai kebutuhan awal", "DNS dan SSL", "Backup mingguan", "Patch dan monitoring dasar", "Review kapasitas berkala"] } },
];

const enData: Record<string, PricingData> = {
  "landing-page": { eyebrow: "LANDING PAGE", name: "Landing Page", price: "IDR 2.5 million", description: "A focused single-page website designed to generate inquiries for products, services, personal brands, or digital campaigns.", features: ["Up to 8 sections", "Custom UI aligned with your brand", "Modern frontend with Next.js/React", "Responsive and mobile-friendly", "Inquiry form and WhatsApp CTA", "Basic SEO, deployment, and SSL", "2 revision rounds and 30-day bug warranty"] },
  "company-profile": { eyebrow: "DIGITAL PRESENCE", name: "Company Profile", price: "IDR 4.5 million", description: "For businesses that need a professional, fast, and discoverable website.", features: ["Up to 7 pages", "Modern frontend with Next.js/React", "Responsive and mobile-friendly", "Contact form and basic SEO", "Deployment and SSL", "30-day bug warranty"] },
  "website-cms": { eyebrow: "BUSINESS SYSTEM", name: "Website + CMS", price: "IDR 10 million", description: "A website with content management or an admin dashboard tailored to the business workflow.", features: ["UI aligned with your brand", "CMS or admin dashboard", "Next.js/React or Laravel as required", "Database and user management", "Email integration", "60-day bug warranty"], recommended: true },
  "web-app": { eyebrow: "CUSTOM WEB SYSTEM", name: "Web App", price: "IDR 20 million", description: "A browser-based application for custom business processes, workflows, and data processing.", features: ["Discovery and workflow mapping", "Next.js/React and Laravel/API as required", "Frontend, backend, database, and APIs", "Roles and access control", "Basic dashboard and reporting", "Testing, deployment, and handover", "60-day bug warranty"] },
  "android-app": { eyebrow: "ANDROID APPLICATION", name: "Android App", price: "IDR 25 million", description: "A custom Android application for operations, customer services, or digital field processes.", features: ["Flutter or native technology as required", "Android UI and core features", "Basic backend and API", "Testing and APK/AAB files", "Google Play submission assistance", "Play Store account and fees excluded", "60-day bug warranty"] },
  "android-ios": { eyebrow: "MULTI-PLATFORM APP", name: "Android + iOS", price: "IDR 50 million", description: "One mobile solution for Android and iOS with an integrated backend and user journey.", features: ["Modern cross-platform development with Flutter", "Android and iOS applications", "Basic backend, database, and API", "Testing and production builds", "Submission assistance for both stores", "Store accounts and fees excluded", "90-day bug warranty"] },
  "server-care-basic": { name: "Server Care Basic", price: "From IDR 500 thousand / server / month", description: "Monitoring, resource checks, SSL checks, and scheduled patching.", features: [] },
  "server-care-pro": { name: "Server Care Pro", price: "From IDR 1.5 million / server / month", description: "More complete monitoring, backup checks, and priority incident support.", features: [] },
  "remote-support": { name: "Remote Support", price: "From IDR 250 thousand / session", description: "Troubleshooting for one issue through a remote connection.", features: [] },
  "server-installation": { name: "Server Installation", price: "From IDR 1.5 million", description: "Linux server installation and configuration based on requirements.", features: [] },
  "domain-hosting-basic": { name: "Domain & Hosting Basic", price: "IDR 1 million / year", description: "For a static landing page or company profile with normal traffic requirements.", features: [".com domain up to IDR 250 thousand", "Static website hosting", "DNS and SSL configuration", "Initial deployment", "Basic uptime monitoring"] },
  "managed-cloud-hosting": { name: "Managed Cloud Hosting", price: "IDR 3 million / year", description: "For a CMS website or small application that needs a runtime, database, and server management.", features: ["Cloud server sized for initial requirements", "DNS and SSL", "Weekly backups", "Basic patching and monitoring", "Periodic capacity review"] },
};

export function fallbackPricing(locale: Locale): PricingRecord[] {
  return idRecords.map((record) => ({ ...record, data: locale === "en" ? enData[record.slug] || record.data : record.data }));
}

export const pricingSeeds = idRecords.map((record) => ({ ...record, dataId: record.data, dataEn: enData[record.slug] || record.data }));
