import path from "node:path";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { renderToBuffer } from "@react-pdf/renderer";
import { InvoicePdf } from "../lib/invoice-pdf";
import type { Invoice } from "../lib/business-documents";

const invoice: Invoice = { id: "sample", invoice_number: "RTD/INV/2026/0001", quotation_id: null, status: "sent", issue_date: "2026-08-24", due_date: "2026-09-07", customer_company: "PT CUSTOMER INDONESIA", customer_name: "Bapak/Ibu PIC", customer_email: "pic@customer.co.id", customer_phone: "+62 812-0000-0000", customer_address: "Jakarta, Indonesia", subject: "Pengembangan Website dan Managed IT Services", items: [{ name: "Website Company Profile", description: "Desain responsif, pengembangan, deployment, SSL, dan garansi bug.", quantity: 1, unit: "paket", unitPrice: 4500000 }, { name: "Managed IT Services", description: "Monitoring, maintenance, backup, dan dukungan remote selama satu bulan.", quantity: 1, unit: "bulan", unitPrice: 2500000 }], discount_amount: 0, payment_account_id: "sample", payment_account_snapshot: { label: "OCBC - Rekening Utama", bank_name: "Bank OCBC", account_name: "PT RETECH DIGITAL SOLUTION", account_number: "693800148498", branch: "", currency: "IDR", instructions: "Cantumkan nomor invoice pada berita transfer." }, payment_terms: "Pembayaran dilakukan melalui transfer ke rekening yang tercantum pada invoice.", notes: "Invoice ini bukan Faktur Pajak dan tidak memuat PPN karena RETECH saat ini Non-PKP.", reminder_enabled: false };
const [logo, signature, stamp] = await Promise.all([readFile(path.join(process.cwd(), "public", "retech-logo-transparent.png")), readFile(path.join(process.cwd(), "public", "documents", "retech-signature.png")), readFile(path.join(process.cwd(), "public", "documents", "retech-stamp-transparent.png"))]);
const pdf = await renderToBuffer(<InvoicePdf invoice={invoice} logoSrc={`data:image/png;base64,${logo.toString("base64")}`} signatureSrc={`data:image/png;base64,${signature.toString("base64")}`} stampSrc={`data:image/png;base64,${stamp.toString("base64")}`} />);
const directory = path.join(process.cwd(), "output", "pdf"); await mkdir(directory, { recursive: true }); await writeFile(path.join(directory, "retech-invoice-template.pdf"), pdf);
