create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.cms_pages (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]*$'),
  label text not null,
  data_id jsonb not null default '{}'::jsonb,
  data_en jsonb not null default '{}'::jsonb,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_services (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]*$'),
  data_id jsonb not null default '{}'::jsonb,
  data_en jsonb not null default '{}'::jsonb,
  published boolean not null default true,
  sort_order integer not null default 99,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_faqs (
  id uuid primary key default gen_random_uuid(),
  question_id text not null,
  answer_id text not null,
  question_en text not null,
  answer_en text not null,
  published boolean not null default true,
  sort_order integer not null default 99,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_pricing (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]*$'),
  section text not null check (section in ('development', 'support', 'hosting')),
  data_id jsonb not null default '{}'::jsonb,
  data_en jsonb not null default '{}'::jsonb,
  published boolean not null default true,
  sort_order integer not null default 99,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_admin_login_codes (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  attempt_count integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists cms_admin_login_codes_lookup
  on public.cms_admin_login_codes (email, created_at desc);

create table if not exists public.cms_audit_log (
  id bigint generated by default as identity primary key,
  actor_email text not null,
  action text not null,
  resource text not null,
  record_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.portfolio_projects
  add column if not exists title_en text,
  add column if not exists category_en text,
  add column if not exists summary_en text,
  add column if not exists challenge_en text,
  add column if not exists solution_en text,
  add column if not exists outcome_en text,
  add column if not exists services_en text[] not null default '{}';

drop trigger if exists cms_pages_set_updated_at on public.cms_pages;
create trigger cms_pages_set_updated_at before update on public.cms_pages
for each row execute function public.set_updated_at();
drop trigger if exists cms_services_set_updated_at on public.cms_services;
create trigger cms_services_set_updated_at before update on public.cms_services
for each row execute function public.set_updated_at();
drop trigger if exists cms_faqs_set_updated_at on public.cms_faqs;
create trigger cms_faqs_set_updated_at before update on public.cms_faqs
for each row execute function public.set_updated_at();
drop trigger if exists cms_pricing_set_updated_at on public.cms_pricing;
create trigger cms_pricing_set_updated_at before update on public.cms_pricing
for each row execute function public.set_updated_at();

alter table public.cms_pages enable row level security;
alter table public.cms_services enable row level security;
alter table public.cms_faqs enable row level security;
alter table public.cms_pricing enable row level security;
alter table public.cms_admin_login_codes enable row level security;
alter table public.cms_audit_log enable row level security;

revoke all on table public.cms_pages from anon, authenticated;
revoke all on table public.cms_services from anon, authenticated;
revoke all on table public.cms_faqs from anon, authenticated;
revoke all on table public.cms_pricing from anon, authenticated;
revoke all on table public.cms_admin_login_codes from anon, authenticated;
revoke all on table public.cms_audit_log from anon, authenticated;

grant all on table public.cms_pages to service_role;
grant all on table public.cms_services to service_role;
grant all on table public.cms_faqs to service_role;
grant all on table public.cms_pricing to service_role;
grant all on table public.cms_admin_login_codes to service_role;
grant all on table public.cms_audit_log to service_role;
grant usage, select on sequence public.cms_audit_log_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'cms-media',
  'cms-media',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

comment on table public.cms_admin_login_codes is
'One-time admin login codes. Service-role access only; never expose through the browser.';
comment on table public.cms_audit_log is
'Append-only audit trail for RETECH CMS mutations.';
