create table if not exists public.portfolio_projects (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null,
  status text not null default 'live' check (status in ('live', 'in-development')),
  summary text not null,
  challenge text not null,
  solution text not null,
  outcome text not null,
  services text[] not null default '{}',
  gallery jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  published boolean not null default false,
  sort_order integer not null default 99,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.portfolio_projects enable row level security;

grant select on table public.portfolio_projects to anon, authenticated;
grant all on table public.portfolio_projects to service_role;
grant usage, select on sequence public.portfolio_projects_id_seq to service_role;

create policy "Public can read published portfolio projects"
on public.portfolio_projects for select
to anon, authenticated
using (published = true);

comment on table public.portfolio_projects is
'Privacy-safe RETECH portfolio metadata. Do not store client names, logos, email addresses, physical addresses, employee names, IP addresses, hostnames, or MAC addresses.';

insert into public.portfolio_projects
  (slug, title, category, status, summary, challenge, solution, outcome, services, gallery, featured, published, sort_order)
values
  (
    'logistics-company-website', 'Logistics Company Website', 'Digital Product', 'live',
    'Platform logistik responsif dengan pelacakan kiriman, pengecekan tarif, serta CMS operasional untuk mengelola shipment, konten, dan pesan customer.',
    'Informasi layanan, status pengiriman, dan estimasi tarif perlu disusun menjadi pengalaman yang mudah dipahami di desktop maupun perangkat mobile.',
    'RETECH merancang company profile, pencarian nomor resi, pengecekan tarif, dan dashboard CMS untuk memantau shipment serta mengelola konten dan inquiry.',
    'Pelanggan dapat mengenali layanan, melacak kiriman, dan mengecek tarif lebih cepat dari satu kanal digital yang terstruktur.',
    array['Shipment Tracking','Rate Checker','Operations CMS','Responsive Web'],
    '[{"src":"/case-studies/logistics/tracking-and-rate-v2.png","alt":"Website pelacakan kiriman dan pengecekan tarif"},{"src":"/case-studies/logistics/cms-dashboard.png","alt":"Dashboard CMS untuk shipment, konten, dan pesan customer"}]'::jsonb,
    true, true, 1
  ),
  (
    'operations-dashboard-cms', 'Operations Dashboard & CMS', 'Business Application', 'live',
    'Dashboard operasional dan CMS terpusat untuk memantau aktivitas, mengelola konten, dan menyederhanakan pekerjaan administratif.',
    'Data operasional dan konten tersebar di beberapa alur kerja, sehingga pembaruan dan pemantauan membutuhkan lebih banyak waktu.',
    'RETECH membangun dashboard ringkas, modul pengelolaan konten, pencarian, pagination, dan kontrol data dalam satu sistem.',
    'Tim dapat membaca kondisi operasional dan memperbarui konten dari satu area kerja yang konsisten.',
    array['Web App','Dashboard','CMS','Role-based Admin'],
    '[{"src":"/case-studies/dashboard-cms/news-cms.png","alt":"Pengelolaan artikel dan alur publikasi News CMS"},{"src":"/case-studies/dashboard-cms/analytics-dashboard.png","alt":"Dashboard analytics untuk metrik penggunaan dan pertumbuhan"},{"src":"/case-studies/dashboard-cms/shipment-cms.png","alt":"Pengelolaan shipment dan pembaruan status operasional"}]'::jsonb,
    true, true, 2
  ),
  (
    'hrms-attendance-platform', 'HRMS & Attendance Platform', 'Business Application', 'live',
    'Sistem HR terintegrasi untuk memantau absensi, keterlambatan, jadwal, cuti, dan laporan administratif dalam satu dashboard.',
    'Tim HR membutuhkan gambaran kehadiran yang cepat tanpa harus merekap data secara manual dari berbagai sumber.',
    'RETECH menyatukan data absensi, filter periode, ringkasan visual, laporan, dan administrasi cuti dalam platform terpusat.',
    'Pemantauan kehadiran menjadi lebih ringkas dan keputusan administratif dapat dibuat dengan data yang lebih mudah dibaca.',
    array['HRMS','Attendance','Reporting','Dashboard Analytics'],
    '[{"src":"/case-studies/hrms/attendance-analytics-v2.png","alt":"Analitik absensi dan keterlambatan"},{"src":"/case-studies/hrms/attendance-percentage-v2.png","alt":"Ringkasan persentase kehadiran"}]'::jsonb,
    true, true, 3
  ),
  (
    'infrastructure-monitoring', 'Infrastructure Monitoring', 'Managed IT', 'live',
    'Control center untuk memantau traffic, utilisasi link, kesehatan router, server, endpoint, layanan, dan sertifikat secara real-time.',
    'Kondisi jaringan harus terlihat secara cepat agar gangguan dan beban berlebih dapat ditangani sebelum berdampak luas.',
    'RETECH membangun dashboard monitoring jaringan dan server dengan indikator kapasitas, endpoint availability, response time, service health, sertifikat TLS, grafik real-time, dan threshold operasional.',
    'Tim IT memperoleh visibilitas terpusat untuk menjaga stabilitas layanan dan merespons anomali lebih awal.',
    array['Network Monitoring','Server Monitoring','Alerting','Managed IT'],
    '[{"src":"/case-studies/infrastructure-monitoring/network-monitor-v2.png","alt":"Dashboard monitoring jaringan, utilisasi link, dan bandwidth real-time"},{"src":"/case-studies/infrastructure-monitoring/server-monitor-v2.png","alt":"Dashboard utilisasi resource, runtime, dan layanan server"},{"src":"/case-studies/infrastructure-monitoring/server-monitoring.png","alt":"Monitoring kesehatan server, endpoint, layanan, dan sertifikat"}]'::jsonb,
    true, true, 4
  ),
  (
    'android-attendance-app', 'Android Attendance App', 'Mobile Application', 'live',
    'Aplikasi Android untuk absensi foto berbasis lokasi dengan timestamp, riwayat kehadiran, serta deteksi indikasi fake dan mock location.',
    'Absensi mobile harus mudah digunakan sekaligus memastikan foto, lokasi, dan waktu kehadiran dapat divalidasi serta tidak mudah dimanipulasi.',
    'RETECH membangun alur check-in dan check-out dengan bukti foto, validasi lokasi, timestamp audit, deteksi fake GPS dan mock location, statistik kehadiran, serta sinkronisasi HRMS.',
    'Tim HR memperoleh data absensi yang lebih dapat diaudit, sementara karyawan dapat melakukan check-in dan check-out langsung dari perangkat Android.',
    array['Photo Attendance','Location Validation','Anti Fake/Mock Location','Timestamp Audit','HRMS Sync'],
    '[{"src":"/case-studies/android-attendance/mobile-home.png","alt":"Beranda absensi Android dengan check-in, check-out, dan timestamp"},{"src":"/case-studies/android-attendance/attendance-admin.png","alt":"Analitik keterlambatan dan administrasi attendance"},{"src":"/case-studies/android-attendance/attendance-history.png","alt":"Riwayat check-in dan check-out dengan timestamp"}]'::jsonb,
    false, true, 5
  )
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  status = excluded.status,
  summary = excluded.summary,
  challenge = excluded.challenge,
  solution = excluded.solution,
  outcome = excluded.outcome,
  services = excluded.services,
  gallery = excluded.gallery,
  featured = excluded.featured,
  published = excluded.published,
  sort_order = excluded.sort_order,
  updated_at = now();
