create table if not exists public.portfolio_projects (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null,
  status text not null default 'live' check (status in ('live', 'in-development')),
  summary text not null,
  challenge text not null,
  solution text not null,
  outcome text not null,
  services text[] not null default '{}',
  gallery jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  published boolean not null default false,
  sort_order integer not null default 99,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.portfolio_projects enable row level security;

grant select on table public.portfolio_projects to anon, authenticated;
grant all on table public.portfolio_projects to service_role;
grant usage, select on sequence public.portfolio_projects_id_seq to service_role;

create policy "Public can read published portfolio projects"
on public.portfolio_projects for select
to anon, authenticated
using (published = true);

comment on table public.portfolio_projects is
'Privacy-safe RETECH portfolio metadata. Do not store client names, logos, email addresses, physical addresses, employee names, IP addresses, hostnames, or MAC addresses.';

insert into public.portfolio_projects
  (slug, title, category, status, summary, challenge, solution, outcome, services, gallery, featured, published, sort_order)
values
  (
    'logistics-company-website', 'Logistics Company Website', 'Digital Product', 'live',
    'Company profile responsif yang merapikan informasi layanan logistik dan memudahkan calon pelanggan menemukan jalur komunikasi yang tepat.',
    'Informasi layanan yang luas perlu disusun menjadi pengalaman digital yang mudah dipahami di desktop maupun perangkat mobile.',
    'RETECH merancang arsitektur halaman, tampilan layanan, alur konversi, dan pengalaman responsif dari tahap eksplorasi sampai inquiry.',
    'Kehadiran digital yang lebih terstruktur, cepat diakses, dan siap mendukung kebutuhan pemasaran perusahaan.',
    array['Company Profile','Responsive Web','UX Structure','Inquiry Flow'],
    '[{"src":"/case-studies/logistics/hero.png","alt":"Tampilan utama website perusahaan logistik"},{"src":"/case-studies/logistics/services.png","alt":"Tampilan layanan website perusahaan logistik"}]'::jsonb,
    true, true, 1
  ),
  (
    'operations-dashboard-cms', 'Operations Dashboard & CMS', 'Business Application', 'live',
    'Dashboard operasional dan CMS terpusat untuk memantau aktivitas, mengelola konten, dan menyederhanakan pekerjaan administratif.',
    'Data operasional dan konten tersebar di beberapa alur kerja, sehingga pembaruan dan pemantauan membutuhkan lebih banyak waktu.',
    'RETECH membangun dashboard ringkas, modul pengelolaan konten, pencarian, pagination, dan kontrol data dalam satu sistem.',
    'Tim dapat membaca kondisi operasional dan memperbarui konten dari satu area kerja yang konsisten.',
    array['Web App','Dashboard','CMS','Role-based Admin'],
    '[{"src":"/case-studies/dashboard-cms/overview.png","alt":"Ringkasan metrik dashboard operasional"},{"src":"/case-studies/dashboard-cms/content-management.png","alt":"Tampilan pengelolaan konten CMS"}]'::jsonb,
    true, true, 2
  ),
  (
    'hrms-attendance-platform', 'HRMS & Attendance Platform', 'Business Application', 'live',
    'Sistem HR terintegrasi untuk memantau absensi, keterlambatan, jadwal, cuti, dan laporan administratif dalam satu dashboard.',
    'Tim HR membutuhkan gambaran kehadiran yang cepat tanpa harus merekap data secara manual dari berbagai sumber.',
    'RETECH menyatukan data absensi, filter periode, ringkasan visual, laporan, dan administrasi cuti dalam platform terpusat.',
    'Pemantauan kehadiran menjadi lebih ringkas dan keputusan administratif dapat dibuat dengan data yang lebih mudah dibaca.',
    array['HRMS','Attendance','Reporting','Dashboard Analytics'],
    '[{"src":"/case-studies/hrms/attendance-analytics.png","alt":"Analitik absensi dan keterlambatan"},{"src":"/case-studies/hrms/attendance-percentage.png","alt":"Ringkasan persentase kehadiran"}]'::jsonb,
    true, true, 3
  ),
  (
    'infrastructure-monitoring', 'Infrastructure Monitoring', 'Managed IT', 'live',
    'Control center untuk memantau traffic, utilisasi link, kesehatan router, dan tren bandwidth secara real-time.',
    'Kondisi jaringan harus terlihat secara cepat agar gangguan dan beban berlebih dapat ditangani sebelum berdampak luas.',
    'RETECH membangun dashboard monitoring dengan indikator kapasitas, status kesehatan, grafik real-time, dan threshold operasional.',
    'Tim IT memperoleh visibilitas terpusat untuk menjaga stabilitas layanan dan merespons anomali lebih awal.',
    array['Network Monitoring','Server Monitoring','Alerting','Managed IT'],
    '[{"src":"/case-studies/infrastructure-monitoring/realtime-overview.png","alt":"Ringkasan monitoring jaringan real-time"},{"src":"/case-studies/infrastructure-monitoring/bandwidth-trend.png","alt":"Grafik tren bandwidth real-time"}]'::jsonb,
    true, true, 4
  ),
  (
    'android-attendance-app', 'Android Attendance App', 'Mobile Application', 'in-development',
    'Aplikasi Android untuk absensi lapangan yang direncanakan terhubung langsung dengan HRMS dan alur verifikasi perusahaan.',
    'Proses absensi mobile membutuhkan pengalaman yang sederhana, validasi yang jelas, dan sinkronisasi data yang aman.',
    'Tahap pengembangan berikutnya berfokus pada alur check-in, validasi lokasi, bukti kehadiran, dan sinkronisasi ke HRMS.',
    'Targetnya adalah pengalaman absensi mobile yang cepat untuk karyawan dan tetap mudah diawasi oleh tim HR.',
    array['Android','Mobile UX','API Integration','HRMS Sync'],
    '[]'::jsonb,
    false, true, 5
  )
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  status = excluded.status,
  summary = excluded.summary,
  challenge = excluded.challenge,
  solution = excluded.solution,
  outcome = excluded.outcome,
  services = excluded.services,
  gallery = excluded.gallery,
  featured = excluded.featured,
  published = excluded.published,
  sort_order = excluded.sort_order,
  updated_at = now();
